database:
    driver: mysql
    connection: root:1234@tcp(127.0.0.1:33306)/hublabs_colleague?charset=utf8&parseTime=True&loc=Local
  behaviorLog:
    kafka:
      brokers:
        - 127.0.0.1:9092
      topic: behaviorlog
  debug: true
  serviceName: colleague-api
  httpPort:     8001
  